runwhen-contrib/rw-public-codecollection

readme_header.md

removed stock readme header and added a couple quick sentences

update header content

---

CODE_OF_CONDUCT.md
README.md
readme_header.md

md extension was incorrectly capitalized

fix md ref

---

codebundles/gcp-opssuite-metricquery/sli.robot
libraries/RW/GCP/OpsSuite.py

Attempts to resolve https://github.com/runwhen-contrib/rw-public-codecollection/issues/11

remove debug values from code

---

README.md
codebundles/prometheus-queryinstant-transform/sli.robot
codebundles/prometheus-queryrange-transform/sli.robot
libraries/RW/Prometheus/Prometheus.py
libraries/RW/Prometheus/robot_tests/query.robot
requirements.txt

- Add a default value option for queries that search for a signal value (result means error, empty means OK)
- Improve secret handling when location services are used (during curl generation)

Refresh prometheus codebundles and add default values options for signal-based queries

---

.github/workflows/generate-index.yml
README.md
codebundles/prometheus-queryinstant-transform/sli.robot
codebundles/prometheus-queryrange-transform/sli.robot

This enables the user to select the raw option to the transformation list. It's been tested successfully to support fixing https://github.com/runwhen-contrib/rw-public-codecollection/issues/22

Add Raw option to promql codebundles

---

codebundles/k8s-daemonset-healthcheck/README.md
codebundles/k8s-daemonset-healthcheck/sli.robot
codebundles/k8s-kubectl-canaryvolumemount/README.md
codebundles/k8s-kubectl-canaryvolumemount/canary_job.yaml
codebundles/k8s-kubectl-canaryvolumemount/canary_pvc.yaml
codebundles/k8s-kubectl-canaryvolumemount/sli.robot
codebundles/k8s-kubectl-eventquery/README.md
codebundles/k8s-kubectl-eventquery/sli.robot
codebundles/k8s-kubectl-run/runbook.robot
codebundles/k8s-kubectl-top/sli.robot
codebundles/k8s-namespace-healthcheck/README.md
codebundles/k8s-namespace-healthcheck/sli.robot
codebundles/k8s-postgres-querymetric/sli.robot
codebundles/k8s-triage-deploymentreplicas/runbook.robot
codebundles/prometheus-queryinstant-transform/README.md
codebundles/prometheus-queryinstant-transform/sli.robot
libraries/RW/K8s/daemonset_tasks_mixin.py
libraries/RW/K8s/job_tasks_mixin.py
libraries/RW/K8s/k8s_connection_mixin.py
libraries/RW/K8s/namespace_tasks_mixin.py
libraries/RW/Utils/utils.py

Adds a suite of new Kubernetes-centric codebundles and various tweaks/fixes:
- K8s Event Query: an SLI which returns the number of events in a namespace matching a regex pattern
- K8s Namespace Healthcheck: an SLI which combines prometheus and namespace event metrics to score a namespace
- K8s Canary Volume: an SLI which periodically spins up a pod and mounts a temporary volume before cleaning it up, validating cluster storage
- K8s Daemonset healthcheck: an SLI that checks the state of a daemonset and returns a score

K8s December Codebundles

---

codebundles/rest-basicauth/README.md
codebundles/rest-basicauth/sli.robot
codebundles/rest-explicitoauth2-basicauth/README.md
codebundles/rest-explicitoauth2-basicauth/sli.robot
codebundles/rest-explicitoauth2-tokenheader/README.md
codebundles/rest-explicitoauth2-tokenheader/sli.robot
codebundles/rest-generic/README.md
codebundles/rest-generic/sli.robot
libraries/RW/Rest/__init__.py
libraries/RW/Rest/rest.py
libraries/RW/Utils/utils.py

Adds REST keywords and codebundles for interacting with REST APIs. While the list of supported flows here is not exhaustive, it should cover the majority of use cases.
- Adds generic REST codebundle which performs an implicit OAuth2 flow
- Adds an alternative codebundle which peforms basic auth
- Adds a REST codebundle which performs an explicit OAuth2 flow with a basic auth access token request
- Adds a REST codebundle which performs an explicit OAuth2 flow with bearer to access token authorization

Rest codebundles v1

---

codebundles/argocd-healthcheck/README.md
codebundles/argocd-healthcheck/sli.robot
libraries/RW/ArgoCD/__init__.py
libraries/RW/ArgoCD/argocd.py

- adds keyword for health checking argocd
- adds general argocd healthcheck codebundle

Add argocd healthcheck codebundle

---

codebundles/hello-world/runbook.robot

add form fields to hello world taskset for testing

---

codebundles/datadog-metricquery/sli.robot
libraries/RW/Datadog/datadog.py

- Correctly type casts the metric response object to allow jmespath to work
- Corrects robot var names

Fix response casting

---

codebundles/curl-generic/README.md
codebundles/k8s-kubectl-get/README.md

Doc updates

---

codebundles/k8s-postgres-query/runbook.robot
codebundles/k8s-postgres-triage/README.md
codebundles/k8s-postgres-triage/runbook.robot
libraries/RW/K8s/k8s_connection_mixin.py
libraries/RW/K8s/k8sutils.py
libraries/RW/K8s/namespace_tasks_mixin.py
libraries/RW/Postgres/postgres.py

This should also close out https://github.com/runwhen-contrib/rw-public-codecollection/issues/54
I'm leaving it as a draft for now until we can successfully test this in the UI. The local version tests fine but we are hitting OOM errors in the UI. 
I also suspect there will be enough discussion and changes here with @jon-funk  - so the draft is opened to start the review process.

K8s postgres triage

---

codebundles/k8s-postgres-query/sli.robot

Adds the needed service to the template

fix postgres template

---

codebundles/k8s-kubectl-namespace-healthcheck/README.md
codebundles/k8s-kubectl-namespace-healthcheck/runbook.robot
codebundles/k8s-kubectl-run/README.md
codebundles/k8s-troubleshoot-deployment/runbook.robot
libraries/RW/K8s/k8s_connection.py
libraries/RW/K8s/namespace_tasks_mixin.py
libraries/RW/Utils/utils.py

- refactors namespace triage codebundle to be more performant / shallower codepath
- disables task stubs in deployment triage for network/pdb
- update k8s client connection class to new static/class pattern

Refactor Namespace Triage codebundle

---

libraries/RW/K8s/namespace_tasks_mixin.py

Fix namespace sli pod status

---

codebundles/k8s-postgres-query/runbook.robot
codebundles/k8s-postgres-query/sli.robot
codebundles/k8s-postgres-triage/runbook.robot
libraries/RW/Postgres/postgres.py

- Fixes quote passthrough
Note: opened for CR but I'm going to test on a few queries in the meantime

Fix k8s postgres quote passthrough

---

libraries/RW/K8s/namespace_tasks_mixin.py

Ignore completed pods status reason

---

codebundles/grpc-grpcurl-unary/README.md
codebundles/grpc-grpcurl-unary/runbook.robot
codebundles/grpc-grpcurl-unary/sli.robot
libraries/RW/Utils/utils.py
libraries/RW/gRPC/__init__.py
libraries/RW/gRPC/grpcurl.py

- adds SLI and taskset for running arbitrary grpcurl commands
Note: currently just Unary method with server reflection is supported.

Add unary grpcurl codebundles

---

libraries/RW/Utils/RWUtils.py

Fix rwutils import error

---

.github/scripts/index.py
codebundles/k8s-kubectl-canaryvolumemount/sli.robot
codebundles/k8s-kubectl-get/sli.robot
codebundles/k8s-kubectl-namespace-healthcheck/runbook.robot
codebundles/k8s-kubectl-namespace-healthcheck/sli.robot
codebundles/k8s-kubectl-run/runbook.robot

- update metadata used to generate index page

Use displayname in metadata

---

.github/workflows/pypi.yaml
MANIFEST.in
setup.cfg
setup.py

- adds config and workflow to automate pypi publish on version bump

Add pypi publish config and workflow

---

libraries/RW/Prometheus/Prometheus.py

Objective: Run `RW.Prometheus` based codebundle against a bare unauthenticated Prometheus endpoint
Codebundle / Robot Script: [Infracloudio/ifc-rw-codecollection/.../runbook.robot](https://github.com/infracloudio/ifc-rw-codecollection/blob/f/codebundle-rds-mysql-conn/codebundles/rds-mysql-conn-count/runbook.robot)
Test Procedure:
- [Dockerfile](https://github.com/infracloudio/ifc-rw-codecollection/blob/f/codebundle-rds-mysql-conn/Dockerfile) 
- Run docker container as follow and we set RW_PATH_TO_ROBOT env
```
docker run --rm -d -p 3000:3000 --name rds-codecollection \
--network="host" \
-e ENV_PROMETHEUS_HOST="http://af2ee8b74f89e4f8a83cd53d3745ccdc-1654255243.us-west-2.elb.amazonaws.com//prometheus/api/v1" \
-e ENV_QUERY="aws_rds_database_connections_average{dimension_DBInstanceIdentifie …
```

Libraries/RW/Prometheus - Optional Headers are now truly optional
